
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface symbols {
  /* terminals */
	public static final int endTag = 1;
    public static final int bodyOpen = 2;
    public static final int bodyClose = 3;
    public static final int frame = 4;
    public static final int framesetOpen = 5;
    public static final int framesetClose = 6;
    public static final int noframesOpen = 7;
    public static final int noframesClose = 8;
    public static final int formOpen = 9;
    public static final int formClose = 10;
    public static final int input = 11;
    public static final int selectOpen = 12;
    public static final int selectClose = 13;
    public static final int optionOpen = 14;
    public static final int optionClose = 15;
    public static final int tableOpen = 16;
    public static final int tableClose = 17;
    public static final int trOpen = 18;
    public static final int trClose = 19;
    public static final int tdOpen = 20;
    public static final int tdClose = 21;
    public static final int thOpen = 22;
    public static final int thClose = 23;
    public static final int thread = 24;
    public static final int tbody = 25;
    public static final int img = 26;
    public static final int aOpen = 27;
    public static final int aClose = 28;
    public static final int ulOpen = 29;
    public static final int ulClose = 30;
    public static final int liOpen = 31;
    public static final int liClose = 32;
    public static final int olOpen = 33;
    public static final int olClose = 34;
    public static final int pOpen = 35;
    public static final int pClose = 36;
    public static final int iOpen = 37;
    public static final int iClose = 38;
    public static final int uOpen = 39;
    public static final int uClose = 40;
    public static final int smallOpen = 41;
    public static final int smallClose = 42;
    public static final int supOpen = 43;
    public static final int supClose = 44;
    public static final int subOpen = 45;
    public static final int subClose = 46;
    public static final int center = 47;
    public static final int fontOpen = 48;
    public static final int fontClose = 49;
    public static final int h1Open = 50;
    public static final int h1Close = 51;
    public static final int h2Open = 52;
    public static final int h2Close = 53;
    public static final int h3Open = 54;
    public static final int h3Close = 55;
    public static final int h4Open = 56;
    public static final int h4Close = 57;
    public static final int h5Open = 58;
    public static final int h5Close = 59;
    public static final int h6Open = 60;
    public static final int h6Close = 61;
    public static final int hr = 62;
    public static final int br = 63;
		               
    public static final int dir	= 64		  ;              
    public static final int id	= 65           ;      
    public static final int lang =66			;
    public static final int onclick =67;
    public static final int ondblclick=68;               
    public static final int onkeydown  = 69;             
    public static final int onkeypress = 70 ;         
    public static final int onkeyup    = 71  ;        
    public static final int onmousedown = 72  ;        
    public static final int onmousemove  = 73  ;    
    public static final int onmouseout   = 74   ;    
    public static final int onmouseover  = 75    ;   
    public static final int onmouseup    = 76     ;
    public static final int contenteditable= 77		;    
    public static final int contextmenu   = 78	     ;  
    public static final int data	= 79	          ;     
    public static final int draggable	= 80	       ;     
    public static final int dropzone    = 81  ;
    public static final int hidden     =  82   ; 
    public static final int spellcheck =  83	;        
    public static final int style       =84	     ;         
    public static final int tabindex   = 85      ;
    public static final int title	=86;


     public static final int accesskey =87   ;
     public static final int charset  =88     ;        
            
     public static final int href     =90       ;        
     public static final int hreflang =91        ;       
     public static final int name     =92         ;       
     public static final int rel      =93         ;       
     public static final int rev      =94          ;      
     public static final int shape    =95           ;    
     
     public static final int target   =97        ;
     public static final int type     =98       ;
     public static final int align    =99        ; 
     public static final int alt      =100        ;      
     public static final int archive  =101         ; 
     public static final int code     =102          ;  
     public static final int codebase =103           ; 
     public static final int height   =104           ;
     public static final int hspace   =105            ;
     public static final int mayscript=106             ;
   
     public static final int vspace   =108           ;
     public static final int width    =109            ;
     public static final int loop     =110             ;
     public static final int background=111         ;
     public static final int bgcolor   =112          ;
     public static final int bgproperties =113        ;  
     public static final int leftmargin   =114       ;
     public static final int clear        =115      ;
  
     
  
}

